import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/lib/providers";
import { CartProvider } from "@/lib/contexts/cart-context";
import { AddressProvider } from "@/lib/contexts/address-context";
import { SelectedItemsProvider } from "@/lib/contexts/selected-items-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LMD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <CartProvider>
            <AddressProvider> 
              <SelectedItemsProvider>{children}</SelectedItemsProvider>
            </AddressProvider>
          </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
