// app/layout.jsx
import { AddressProvider } from "@/lib/contexts/address-context";
import { CartProvider } from "@/lib/contexts/cart-context";
import { SelectedItemsProvider } from "@/lib/contexts/selected-items-context";
import SessionProviderWrapper from "@/lib/NextAuthProvider/SessionProviderWrapper";
import { Providers } from "@/lib/providers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProductProvider } from "@/lib/contexts/productContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LMD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SessionProviderWrapper>
            <CartProvider showCartInHeader={true}>
              <ProductProvider>
                <AddressProvider>
                  <SelectedItemsProvider>
                    {children}
                  </SelectedItemsProvider>
                </AddressProvider>
              </ProductProvider>
            </CartProvider>
          </SessionProviderWrapper>
        </Providers>
      </body>
    </html>
  );
}
