// app/layout.jsx
import { CartProvider } from "@/lib/contexts/cart-context";
import { SelectedItemsProvider } from "@/lib/contexts/selected-items-context";
import { DiscountProvider } from "@/lib/contexts/discount-context";
import SessionProviderWrapper from "@/lib/NextAuthProvider/SessionProviderWrapper";
import { Providers } from "@/lib/providers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProductProvider } from "@/lib/contexts/productContext";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/app/components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LMD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Providers>
          <SessionProviderWrapper>
            <AuthProvider>
              <CartProvider showCartInHeader={true}>
                <ProductProvider>
                  <SelectedItemsProvider>
                    <DiscountProvider>
                      <Toaster />
                      {children}
                    </DiscountProvider>
                  </SelectedItemsProvider>
                </ProductProvider>
              </CartProvider>
            </AuthProvider>
          </SessionProviderWrapper>
        </Providers>
      </body>
    </html>
  );
}